# Generated by Django 5.0.6 on 2024-06-08 17:41

import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_vendor_date_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default='vendor.jpg', upload_to=index.models.user_directory_path),
        ),
    ]
