# Generated by Django 5.0.6 on 2024-06-08 17:57

import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_vendor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='vendor.jpg', upload_to=index.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(upload_to=index.models.user_directory_path),
        ),
    ]
