# Generated by Django 5.0.6 on 2024-06-09 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_vendor_cover_image_alter_vendor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimges',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_image', to='index.product'),
        ),
    ]
