# Generated by Django 5.0.6 on 2024-06-12 13:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='demo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
